/*
 * generated by Xtext
 */
package com.evrasoft.sling.ui.contentassist

import com.evrasoft.sling.ui.contentassist.AbstractSlingContentProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class SlingContentProposalProvider extends AbstractSlingContentProposalProvider {
}
