/*
 * generated by Xtext
 */
package com.evrasoft.sling.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.linking.ILinkingDiagnosticMessageProvider;

import com.evrasoft.sling.ui.linking.SlingLinkingDiagnosticMessageProvider;

/**
 * Use this class to register components to be used within the IDE.
 */
public class SlingContentUiModule extends com.evrasoft.sling.ui.AbstractSlingContentUiModule {
	public SlingContentUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}

	@Override
	public Class<? extends org.eclipse.xtext.ui.editor.contentassist.IContentProposalProvider> bindIContentProposalProvider() {
		return com.evrasoft.sling.ui.contentassist.SlingContentProposalProvider2.class;
	}

	public Class<? extends ILinkingDiagnosticMessageProvider> bindILinkingDiagnosticMessageProvider() {
		return SlingLinkingDiagnosticMessageProvider.class;
	}

}
