/*
* generated by Xtext
*/
package com.evrasoft.sling;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class SlingContentStandaloneSetup extends SlingContentStandaloneSetupGenerated{

	public static void doSetup() {
		new SlingContentStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

